version: '3.9'

services:
  book_catalog:
    build:
      context: ./book_catalog
    image: book_catalog
    environment:
      - DATABASE_URL="postgresql://s224169428_user:ksCozU984iGsAqoB7QSniIFRb7HMjhMv@dpg-crah25aj1k6c73bvm0l0-a.oregon-postgres.render.com/s224169428"

    ports:
      - "8000:8000"

  inventory_management:
    build:
      context: ./inventory_management
    image: inventory_management
    environment:
      - DATABASE_URL="postgresql://s224169428_user:ksCozU984iGsAqoB7QSniIFRb7HMjhMv@dpg-crah25aj1k6c73bvm0l0-a.oregon-postgres.render.com/s224169428"

    ports:
      - "7000:7000"
